### PR TITLE
award blog post

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Review by pat-s — COMMENTED** [review]
Thanks Lars! Just to stay consistent: 
Every sentence should go on its own line.
Looks like you've got some word wrapping enabled which auto-breaks at a certain width.

**Comment by larskotthoff** [comment]
Thanks, fixed.

**Review by mllg — APPROVED** [review]

**Comment by pat-s** [comment]
Thanks Lars. I've added the HTML manually.

Would you mind adding the post also to https://github.com/rweekly/rweekly.org? Thanks!

**Comment by larskotthoff** [comment]
Happy to do that, but how do images work? The instructions aren't very clear on this -- how do I get images on raw.githubusercontent.com?

**Comment by pat-s** [comment]
In this case it is not about republishing on r-weekly.org but just adding the link of our blog pos under a category on r-weekly that fits.

**Comment by larskotthoff** [comment]
Ah ok -- done.

**Pull request merged**
