### PR TITLE
mlr3cluster blogpost draft

### PR DESCRIPTION
**Pull request by damirpolat**
I created a draft for a blogpost introducing mlr3cluster extension package. The post will probably be revised, but I want to get some feedback from the mlr3 community. 

Thanks, 
Damir

### CODE REVIEW

**Comment by pat-s** [comment]
Hi Damir, 

Thanks for the post. Please use the [mlr-style](https://github.com/mlr-org/mlr3/wiki/Style-Guide) throughout the document.
Also it is good practice to use one line per sentence and start each sentence on a new line.

**Comment by damirpolat** [comment]
Hey Patrick, 
Thanks for noticing, I didn't even realize that styling is applied to blogposts as well. I just fixed the styling problems. 


Thanks, 
Damir

**Comment by larskotthoff** [comment]
Unless anybody objects, I'll merge this in the next few days @pat-s @damirpolat

**Comment by mllg** [comment]
ACAICT the blog is not part of rbloggers anymore. If you publish before sorting it out, nobody will see it :/

**Comment by pat-s** [comment]
How can we verify this? I do not understand why there is no notification when a blog is removed or even a method to verify this.

We have r-bloggers in our blogroll and the feed export was fine last time. I can't think of any reasons why we should have been dropped...

**Comment by mllg** [comment]
You can verify by simply searching r-bloggers.com for "mlr3" or "mlr3pipelines". The last post is not listed.

**Comment by mllg** [comment]
Maybe we got removed because we don't have a linkback to r-bloggers.com	?

**Comment by PhilippPro** [comment]
Edit: I guess you are right, I couldnt find the last blog post from this list: https://mlr-org.com/docs/

You should give a link to R-Bloggers, that is a must.

**Comment by pat-s** [comment]
As said, we have a linkback since I restyled the blog some time ago: https://mlr-org.com/blogroll/.

And we had this when we were still in/re-entered last time.

**Comment by PhilippPro** [comment]
Then just ask the guy who is in charge of r bloggers.

**Comment by pat-s** [comment]
> Then just ask the guy who is in charge of r bloggers.

I'm tired of it since I did that at least 5 times already (no joke). And I know from other persons that had similar experiences and opted out of r-bloggers.

If someone has the motivation, feel free to clear up the situation (again).

**Comment by PhilippPro** [comment]
For me he answered quickly. Probably he is quite busy. ;)

**Comment by damirpolat** [comment]
> > Then just ask the guy who is in charge of r bloggers.
> 
> I'm tired of it since I did that at least 5 times already (no joke). And I know from other persons that had similar experiences and opted out of r-bloggers.
> 
> If someone has the motivation, feel free to clear up the situation (again).

I can do that. 
To make sure, it is just filling out this form -- https://www.r-bloggers.com/add-your-blog/ ?

**Comment by damirpolat** [comment]
> > > Then just ask the guy who is in charge of r bloggers.
> > 
> > 
> > I'm tired of it since I did that at least 5 times already (no joke). And I know from other persons that had similar experiences and opted out of r-bloggers.
> > If someone has the motivation, feel free to clear up the situation (again).
> 
> I can do that.
> To make sure, it is just filling out this form -- https://www.r-bloggers.com/add-your-blog/ ?

He got back to me. It looks like the feed doesn't show the images properly. Once that's fixed, he will add mlr back to his blog. 

http://feeds.feedburner.com/mlr-org/Jcbx

Example: 

thumbnail_image

His suggestion:
>  Could you please set the image url to use absolute URLs? (some feed fetchers get it right and some don't)

**Comment by damirpolat** [comment]
I fixed the links and instructions now that cluster and latest viz packages are on CRAN. I added everything I wanted to add to the post. Should be good to go.

**Comment by larskotthoff** [comment]
Thanks -- unless anybody objects, I'll merge this in the next few days.

**Comment by mllg** [comment]
> Thanks -- unless anybody objects, I'll merge this in the next few days.

Fine for me. Is the blog repaired and in rbloggers again? @jakob-r @be-marc

**Pull request merged**
