### PR TITLE
mlr example for drake

### PR DESCRIPTION
**Pull request by pat-s**
A small note that a mlr example is now available for drake.

@larskotthoff Could you have a look?

cc @wlandau (with netlify preview)

### CODE REVIEW

**Comment by wlandau** [comment]
Very exciting, @pat-s!

**Comment by larskotthoff** [comment]
Could you have an example in the blog post please? At the moment it feels like something is missing.

**Comment by jakob-r** [comment]
The title could be a bit more catchy: "Reproducible mlr workflow using/for drake",

**Comment by pat-s** [comment]
@larskotthoff The blog post shows how to init the example. This will download a whole directory containing the example. There is not much more that I could show directly in the blog post.

@jakob-r True. Will update it :+1:

**Comment by pat-s** [comment]
@jakob-r Better? Then I'll publish the post.

**Pull request merged**
